# Generated by Django 3.0.12 on 2021-02-08 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_id", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_id", models.CharField(max_length=255)),
                ("user_name", models.CharField(max_length=255)),
                ("user_image", models.URLField(max_length=255)),
                ("content", models.TextField(null=True)),
                ("score", models.PositiveIntegerField()),
                ("thumbs_up_count", models.PositiveIntegerField()),
                ("review_created_version", models.CharField(max_length=50, null=True)),
                ("at", models.DateTimeField()),
                ("reply_content", models.TextField(null=True)),
                ("replied_at", models.DateTimeField(null=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crawler.App"
                    ),
                ),
            ],
        ),
    ]
